[package]
name = "slash-command-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "*"

[dependencies.serenity]
version = "*"
default-features = false
features = ["rustls_backend", "client", "gateway", "builder"]
