[package]
name = "slash-command-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "*", default-features = false }
sqlx = { version = "*", default-features = false, features = ["postgres"] }

[dependencies.serenity]
version = "*"
default-features = false
features = ["rustls_backend", "client", "gateway", "builder"]
